apiVersion: batch/v1
kind: Job
metadata:
  name: artifacts
  namespace: hlf
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: create-artifacts
      namespace: hlf
    spec:
      containers:
        - name: artifacts
          image: hyperledger/fabric-tools:2.4
          workingDir: /
          resources:
            requests:
              memory: "900Mi"
              cpu: "900m"
            limits:
              memory: "900Mi"
              cpu: "900m"
          volumeMounts:
            - mountPath: /organizations
              name: fabricfiles
              subPath: organizations
            - mountPath: /configtx
              name: fabricfiles
              subPath: configtx
            - mountPath: /system-genesis-block
              name: fabricfiles
              subPath: system-genesis-block
            - mountPath: /channel-artifacts
              name: fabricfiles
              subPath: channel-artifacts
            - mountPath: /scripts
              name: fabricfiles
              subPath: scripts
          command:
            - /bin/bash
            - -c
            - |
              ./scripts/createGenesis.sh &&
              ./scripts/createChannel.sh
      restartPolicy: Never
      volumes:
        - name: fabricfiles
          persistentVolumeClaim:
            claimName: pvc-local-one
