apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-local-one
  labels:
    type: local
    count: one
    capacity: 5gb
spec:
  #we use local node storage here!
  #kubectl get storageclass
  storageClassName: hostpath
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/run/desktop/mnt/host/e/kube_pv"
