apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-local-one
  namespace: hlf
spec:
  storageClassName: hostpath
  selector:
    matchLabels:
      type: local
      count: one
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2048Mi
