apiVersion: batch/v1
kind: Job
metadata:
  name: create-certs
  namespace: hlf
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: create-certs
      namespace: hlf
    spec:
      volumes:
        - name: fabricfiles
          persistentVolumeClaim:
            claimName: pvc-local-one
      containers:
        - name: create-certs
          image: hyperledger/fabric-ca-tools:latest
          resources:
            requests:
              memory: "900Mi"
              cpu: "900m"
            limits:
              memory: "900Mi"
              cpu: "900m"
          volumeMounts:
            - mountPath: /organizations
              name: fabricfiles
              subPath: organizations
            - mountPath: /scripts
              name: fabricfiles
              subPath: scripts
          command:
            - /bin/sh
            - -c
            - |
              ./scripts/orderer-certs.sh &&
              ./scripts/org1-certs.sh &&
              ./scripts/org2-certs.sh &&
              ./scripts/org3-certs.sh
      restartPolicy: Never
