apiVersion: v1
kind: Service
metadata:
  name: basic-org2
  namespace: hlf
  labels:
    app: basic-org2
spec:
  ports:
    - name: grpc
      port: 7052
      targetPort: 7052
  selector:
    app: chaincode-basic-org2
